version: "3"
services:
  client:
    build: ./web_client
    depends_on:
      - server
    container_name: male-club-client
    network_mode: "host"
  server:
    build: ./server
    ports:
      - "8080:8080"
    container_name: male-club-server
